version: "3"
services:
  bootcamp-rocketseat-docker:
    stdin_open: true
    tty: true
    container_name: bootcamp-rocketseat-docker
    restart: "no"
    image: marcellocosta/bootcamp-rocketseat-docker
    environment:
        DISPLAY: ":0"
    volumes:
    #    - "$HOME/.Xauthority:/root/.Xauthority:rw"
        - "./developer:/home/developer"
    network_mode: "host"
    build:
        dockerfile: Dockerfile
        context: .

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - "./developer/mongodb :/data/db"
    network_mode: "host"
